<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {{--  Bootstrap  --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Lakbay Agapay Summary Report</title>
    <style>
        html{
            font-size: 9pt;
            /*height: 1248px;*/
        }
        #logo{
            width: 200px;
        }
        #title{
            margin-top: 15px;
            text-align: center;
            font-size: 20pt;
        }
        #visitors{
            width: 100%;
            text-align: center;
        }
        table{
            width: 100%;
            text-align: center;
        }
        td{
            padding-top: 10px;
            padding-bottom: 10px;
        }
        #visitors {
            border-collapse: collapse;
        }
        #visitors td, #visitors th {
            border: 1px solid gray;
        }
        #visitors tr:first-child th {
            border-top: 0;
        }
        #visitors tr th:first-child {
            border-left: 0;
        }
        #visitors tr th:last-child {
            border-right: 0;
        }
        #destination-table{
            max-height: 300px;
            text-align: left;
            width: 100%;
            margin-right: auto;
            margin-left: auto;
        }
        #destination-table td{
            padding-top: 0;
            padding-bottom: 0;
        }
        #contributor-table td{
            text-align: center;
            padding-top: 2px;
            padding-bottom: 0;
        }
    </style>
</head>
<body>
    <div style="margin-left: 60px; margin-right: 60px;">
        <div>
            <img src="{{ public_path().'/img/icons/LOGO-BANNER-INVERTED.jpg' }}" id="logo">
            <div style="float: right">
                <span>Generated By: {{ $user->user_fname." ".$user->user_mname." ".$user->user_lname." (".$user->user_type.")" }}</span>
                <br>
                <span style="float: right">Date: {{ $date }}</span><br>
                <span style="float: right">Time: {{ $time }}</span>
            </div>
        </div>
        <br>
        <div>
            <h1 id="title">Summary Report</h1>
        </div>
        <br>
        <br>
        <div>
            <table id="user-table">
                <tr>
                    <th colspan="5" style="background-color: #ebebeb; height: 25px;">
                        Users
                    </th>
                </tr>
                <tr>
                    <td>Total: <b>{{ $user_count->count() }}</b></td>
                    <td>Tourists: <b>{{ $user_count->where('user_type','Tourist')->count() }}</b></td>
                    <td>Tour Operators: <b>{{ $user_count->where('user_type','Tour Operator')->count() }}</b></td>
                    <td>Admins: <b>{{ $user_count->where('user_type','Admin')->count() }}</b></td>
                    <td>Super Admins: <b>{{ $user_count->where('user_type','Super Admin')->count() }}</b></td>
                </tr>
            </table>
        </div>
        <br>
        <br>
        <div>
            <table id="visitors">
                <tr>
                    <th colspan="13" style="background-color: #ebf4ff; height: 25px;">
                        Lakbay Agapay Visitors Last Year (2021)
                    </th>
                </tr>
                <tr>
                    <td>Jan</td>
                    <td>Feb</td>
                    <td>Mar</td>
                    <td>Apr</td>
                    <td>May</td>
                    <td>Jun</td>
                    <td>Jul</td>
                    <td>Aug</td>
                    <td>Sep</td>
                    <td>Oct</td>
                    <td>Nov</td>
                    <td>Dec</td>
                    <td>Total</td>
                </tr>
                <tr>
                    <td>{{ $last_jan }}</td>
                    <td>{{ $last_feb }}</td>
                    <td>{{ $last_mar }}</td>
                    <td>{{ $last_apr }}</td>
                    <td>{{ $last_may }}</td>
                    <td>{{ $last_jun }}</td>
                    <td>{{ $last_jul }}</td>
                    <td>{{ $last_aug }}</td>
                    <td>{{ $last_sep }}</td>
                    <td>{{ $last_oct }}</td>
                    <td>{{ $last_nov }}</td>
                    <td>{{ $last_dec }}</td>
                    <td>{{ $last_total }}</td>
                </tr>
            </table>
        </div>
        <br>
        <br>
        <div>
            <table id="visitors">
                <tr>
                    <th colspan="13" style="background-color: #ebf4ff; height: 25px;">
                        Lakbay Agapay Visitors This Year (2022)
                    </th>
                </tr>
                <tr>
                    <td>Jan</td>
                    <td>Feb</td>
                    <td>Mar</td>
                    <td>Apr</td>
                    <td>May</td>
                    <td>Jun</td>
                    <td>Jul</td>
                    <td>Aug</td>
                    <td>Sep</td>
                    <td>Oct</td>
                    <td>Nov</td>
                    <td>Dec</td>
                    <td>Total</td>
                </tr>
                <tr>
                    <td>{{ $cur_jan }}</td>
                    <td>{{ $cur_feb }}</td>
                    <td>{{ $cur_mar }}</td>
                    <td>{{ $cur_apr }}</td>
                    <td>{{ $cur_may }}</td>
                    <td>{{ $cur_jun }}</td>
                    <td>{{ $cur_jul }}</td>
                    <td>{{ $cur_aug }}</td>
                    <td>{{ $cur_sep }}</td>
                    <td>{{ $cur_oct }}</td>
                    <td>{{ $cur_nov }}</td>
                    <td>{{ $cur_dec }}</td>
                    <td>{{ $cur_total }}</td>
                </tr>
            </table>
        </div>
        <br>
        <br>
        <div>
            <table id="user-table">
                <tr>
                    <th colspan="3" style="background-color: #c4e3ba; height: 25px;">
                        Destination
                    </th>
                </tr>
                <tr>
                    <td>Approved: <b>{{ $dest_approved }}</b></td>
                    <td>Pending: <b>{{ $dest_pending }}</b></td>
                    <td>Rejected: <b>{{ $dest_rejected }}</b></td>
                </tr>
            </table>
            <table id="destination-table">
                <tr>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Most Viewed
                        <br>
                        <text style="font-weight: normal; font-size: 8pt">
                            @if($most_viewed_destination_from != "" && $most_viewed_destination_to != "")
                                ({{ $most_viewed_destination_from }}) - ({{ $most_viewed_destination_to }})
                            @else
                                (All Time)
                            @endif
                        </text>
                    </th>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Top Rated
                        <br>
                        <text style="font-weight: normal; font-size: 8pt">
                            @if($top_rated_destination_from != "" && $top_rated_destination_to != "")
                                ({{ $top_rated_destination_from }}) - ({{ $top_rated_destination_to }})
                            @else
                                (All Time)
                            @endif
                        </text>
                    </th>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Top Favorites
                        <br>
                    </th>
                </tr>
                <tr>
                    <td>1. @if(count($topDestinations) >= 1) {{ $topDestinations[0] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[0] }})</text> @else -- @endif </td>
                    <td>1. @if(count($top_rated_destinations) >= 1) {{ $top_rated_destinations[0][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[0][1] }})</text> @else -- @endif </td>
                    <td>1. @if(count($favDestinations) >= 1) {{ $favDestinations[0]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[0]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>2. @if(count($topDestinations) >= 2) {{ $topDestinations[1] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[1] }})</text> @else -- @endif </td>
                    <td>2. @if(count($top_rated_destinations) >= 2) {{ $top_rated_destinations[1][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[1][1] }})</text> @else -- @endif </td>
                    <td>2. @if(count($favDestinations) >= 2) {{ $favDestinations[1]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[1]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>3. @if(count($topDestinations) >= 3) {{ $topDestinations[2] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[2] }})</text> @else -- @endif </td>
                    <td>3. @if(count($top_rated_destinations) >= 3) {{ $top_rated_destinations[2][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[2][1] }})</text> @else -- @endif </td>
                    <td>3. @if(count($favDestinations) >= 3) {{ $favDestinations[2]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[2]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>4. @if(count($topDestinations) >= 4) {{ $topDestinations[3] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[3] }})</text> @else -- @endif </td>
                    <td>4. @if(count($top_rated_destinations) >= 4) {{ $top_rated_destinations[3][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[3][1] }})</text> @else -- @endif </td>
                    <td>4. @if(count($favDestinations) >= 4) {{ $favDestinations[3]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[3]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>5. @if(count($topDestinations) >= 5) {{ $topDestinations[4] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[4] }})</text> @else -- @endif </td>
                    <td>5. @if(count($top_rated_destinations) >= 5) {{ $top_rated_destinations[4][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[4][1] }})</text> @else -- @endif </td>
                    <td>5. @if(count($favDestinations) >= 5) {{ $favDestinations[4]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[4]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>6. @if(count($topDestinations) >= 6) {{ $topDestinations[5] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[5] }})</text> @else -- @endif </td>
                    <td>6. @if(count($top_rated_destinations) >= 6) {{ $top_rated_destinations[5][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[5][1] }})</text> @else -- @endif </td>
                    <td>6. @if(count($favDestinations) >= 6) {{ $favDestinations[5]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[5]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>7. @if(count($topDestinations) >= 7) {{ $topDestinations[6] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[6] }})</text> @else -- @endif </td>
                    <td>7. @if(count($top_rated_destinations) >= 7) {{ $top_rated_destinations[6][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[6][1] }})</text> @else -- @endif </td>
                    <td>7. @if(count($favDestinations) >= 7) {{ $favDestinations[6]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[6]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>8. @if(count($topDestinations) >= 8) {{ $topDestinations[7] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[7] }})</text> @else -- @endif </td>
                    <td>8. @if(count($top_rated_destinations) >= 8) {{ $top_rated_destinations[7][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[7][1] }})</text> @else -- @endif </td>
                    <td>8. @if(count($favDestinations) >= 8) {{ $favDestinations[7]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[7]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>9. @if(count($topDestinations) >= 9) {{ $topDestinations[8] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[8] }})</text> @else -- @endif </td>
                    <td>9. @if(count($top_rated_destinations) >= 9) {{ $top_rated_destinations[8][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[8][1] }})</text> @else -- @endif </td>
                    <td>9. @if(count($favDestinations) >= 9) {{ $favDestinations[8]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[8]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>10. @if(count($topDestinations) >= 10) {{ $topDestinations[9] }} <text style="color: gray; font-size: 8pt;">({{ $topDestinationsViews[9] }})</text> @else -- @endif </td>
                    <td>10. @if(count($top_rated_destinations) >= 10) {{ $top_rated_destinations[9][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_destinations[9][1] }})</text> @else -- @endif </td>
                    <td>10. @if(count($favDestinations) >= 10) {{ $favDestinations[9]['dest_name'] }} <text style="color: gray; font-size: 8pt;">({{ $favDestinations[9]['Points'] }})</text> @else -- @endif </td>
                </tr>
            </table>
        </div>
        <br>
        <div style="margin-top: 300px">
            <table id="user-table">
                <tr>
                    <th colspan="3" style="background-color: #ffede3; height: 25px;">
                        Tour Operator
                    </th>
                </tr>
                <tr>
                    <td>Approved: <b>{{ $to_approved }}</b></td>
                    <td>Pending: <b>{{ $to_pending }}</b></td>
                    <td>Rejected: <b>{{ $to_rejected }}</b></td>
                </tr>
            </table>
            <table id="destination-table">
                <tr>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Most Viewed
                        <br>
                        <text style="font-weight: normal; font-size: 8pt">
                            @if($most_viewed_operator_from != "" && $most_viewed_operator_to != "")
                                ({{ $most_viewed_operator_from }}) - ({{ $most_viewed_operator_to }}
                            @else
                                (All Time)
                            @endif
                        </text>
                    </th>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Top Rated
                        <br>
                        <text style="font-weight: normal; font-size: 8pt">
                            @if($top_rated_operator_from != "" && $top_rated_operator_to != "")
                                ({{ $top_rated_operator_from }}) - ({{ $top_rated_operator_to }})
                            @else
                                (All Time)
                            @endif
                        </text>
                    </th>
                    <th class="col-4" style="padding-bottom: 10px; font-size: 11pt;">
                        Top Favorites
                        <br>
                    </th>
                </tr>
                <tr>
                    <td>1. @if(count($topOperators) >= 1) {{ $topOperators[0] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[0] }})</text> @else -- @endif </td>
                    <td>1. @if(count($top_rated_operators) >= 1) {{ $top_rated_operators[0][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[0][1] }})</text> @else -- @endif </td>
                    <td>1. @if(count($favOperators) >= 1) {{ $favOperators[0]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[0]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>2. @if(count($topOperators) >= 2) {{ $topOperators[1] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[1] }})</text> @else -- @endif </td>
                    <td>2. @if(count($top_rated_operators) >= 2) {{ $top_rated_operators[1][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[1][1] }})</text> @else -- @endif </td>
                    <td>2. @if(count($favOperators) >= 2) {{ $favOperators[1]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[1]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>3. @if(count($topOperators) >= 3) {{ $topOperators[2] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[2] }})</text> @else -- @endif </td>
                    <td>3. @if(count($top_rated_operators) >= 3) {{ $top_rated_operators[2][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[2][1] }})</text> @else -- @endif </td>
                    <td>3. @if(count($favOperators) >= 3) {{ $favOperators[2]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[2]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>4. @if(count($topOperators) >= 4) {{ $topOperators[3] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[3] }})</text> @else -- @endif </td>
                    <td>4. @if(count($top_rated_operators) >= 4) {{ $top_rated_operators[3][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[3][1] }})</text> @else -- @endif </td>
                    <td>4. @if(count($favOperators) >= 4) {{ $favOperators[3]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[3]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>5. @if(count($topOperators) >= 5) {{ $topOperators[4] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[4] }})</text> @else -- @endif </td>
                    <td>5. @if(count($top_rated_operators) >= 5) {{ $top_rated_operators[4][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[4][1] }})</text> @else -- @endif </td>
                    <td>5. @if(count($favOperators) >= 5) {{ $favOperators[4]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[4]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>6. @if(count($topOperators) >= 6) {{ $topOperators[5] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[5] }})</text> @else -- @endif </td>
                    <td>6. @if(count($top_rated_operators) >= 6) {{ $top_rated_operators[5][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[5][1] }})</text> @else -- @endif </td>
                    <td>6. @if(count($favOperators) >= 6) {{ $favOperators[5]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[5]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>7. @if(count($topOperators) >= 7) {{ $topOperators[6] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[6] }})</text> @else -- @endif </td>
                    <td>7. @if(count($top_rated_operators) >= 7) {{ $top_rated_operators[6][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[6][1] }})</text> @else -- @endif </td>
                    <td>7. @if(count($favOperators) >= 7) {{ $favOperators[6]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[6]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>8. @if(count($topOperators) >= 8) {{ $topOperators[7] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[7] }})</text> @else -- @endif </td>
                    <td>8. @if(count($top_rated_operators) >= 8) {{ $top_rated_operators[8][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[7][1] }})</text> @else -- @endif </td>
                    <td>8. @if(count($favOperators) >= 8) {{ $favOperators[7]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[7]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>9. @if(count($topOperators) >= 9) {{ $topOperators[8] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[8] }})</text> @else -- @endif </td>
                    <td>9. @if(count($top_rated_operators) >= 9) {{ $top_rated_operators[8][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[8][1] }})</text> @else -- @endif </td>
                    <td>9. @if(count($favOperators) >= 9) {{ $favOperators[8]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[8]['Points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>10. @if(count($topOperators) >= 10) {{ $topOperators[9] }} <text style="color: gray; font-size: 8pt;">({{ $topOperatorsViews[8] }})</text> @else -- @endif </td>
                    <td>10. @if(count($top_rated_operators) >= 10) {{ $top_rated_operators[9][0] }} <text style="color: gray; font-size: 8pt;">({{ $top_rated_operators[9][1] }})</text> @else -- @endif </td>
                    <td>10. @if(count($favOperators) >= 10) {{ $favOperators[9]['operator_company'] }} <text style="color: gray; font-size: 8pt;">({{ $favOperators[9]['Points'] }})</text> @else -- @endif </td>
                </tr>
            </table>
        </div>
        <br>
        <br>
        <div>
            <table id="contributor-table">
                <tr>
                    <th colspan="2" style="background-color: #fffec9; height: 25px;">
                        Top Contributors
                    </th>
                </tr>
                <tr>
                    <td class="col-6">1. @if(count($contributors) >= 1) {{ $contributors[0]['user_fname'] }} {{ $contributors[0]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[0]['points'] }})</text> @else -- @endif </td>
                    <td class="col-6">11. @if(count($contributors) >= 11) {{ $contributors[10]['user_fname'] }} {{ $contributors[10]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[10]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>2. @if(count($contributors) >= 2) {{ $contributors[1]['user_fname'] }} {{ $contributors[1]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[1]['points'] }})</text> @else -- @endif </td>
                    <td>12. @if(count($contributors) >= 12) {{ $contributors[11]['user_fname'] }} {{ $contributors[11]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[11]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>3. @if(count($contributors) >= 3) {{ $contributors[2]['user_fname'] }} {{ $contributors[2]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[2]['points'] }})</text> @else -- @endif </td>
                    <td>13. @if(count($contributors) >= 13) {{ $contributors[12]['user_fname'] }} {{ $contributors[12]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[12]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>4. @if(count($contributors) >= 4) {{ $contributors[3]['user_fname'] }} {{ $contributors[3]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[3]['points'] }})</text> @else -- @endif </td>
                    <td>14. @if(count($contributors) >= 14) {{ $contributors[13]['user_fname'] }} {{ $contributors[13]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[13]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>5. @if(count($contributors) >= 5) {{ $contributors[4]['user_fname'] }} {{ $contributors[4]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[4]['points'] }})</text> @else -- @endif </td>
                    <td>15. @if(count($contributors) >= 15) {{ $contributors[14]['user_fname'] }} {{ $contributors[14]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[14]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>6. @if(count($contributors) >= 6) {{ $contributors[5]['user_fname'] }} {{ $contributors[5]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[5]['points'] }})</text> @else -- @endif </td>
                    <td>16. @if(count($contributors) >= 16) {{ $contributors[15]['user_fname'] }} {{ $contributors[15]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[5]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>7. @if(count($contributors) >= 7) {{ $contributors[6]['user_fname'] }} {{ $contributors[6]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[6]['points'] }})</text> @else -- @endif </td>
                    <td>17. @if(count($contributors) >= 17) {{ $contributors[16]['user_fname'] }} {{ $contributors[16]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[16]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>8. @if(count($contributors) >= 8) {{ $contributors[7]['user_fname'] }} {{ $contributors[7]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[7]['points'] }})</text> @else -- @endif </td>
                    <td>18. @if(count($contributors) >= 18) {{ $contributors[17]['user_fname'] }} {{ $contributors[17]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[17]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>9. @if(count($contributors) >= 9) {{ $contributors[8]['user_fname'] }} {{ $contributors[8]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[8]['points'] }})</text> @else -- @endif </td>
                    <td>19. @if(count($contributors) >= 19) {{ $contributors[18]['user_fname'] }} {{ $contributors[18]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[18]['points'] }})</text> @else -- @endif </td>
                </tr>
                <tr>
                    <td>10. @if(count($contributors) >= 10) {{ $contributors[9]['user_fname'] }} {{ $contributors[9]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[9]['points'] }})</text> @else -- @endif </td>
                    <td>20. @if(count($contributors) >= 20) {{ $contributors[19]['user_fname'] }} {{ $contributors[19]['user_lname'] }}<text style="color: gray; font-size: 8pt;">({{ $contributors[19]['points'] }})</text> @else -- @endif </td>
                </tr>
            </table>
        </div>



    </div>
</body>
</html>
