<?php

namespace Database\Seeders;

use App\Models\Destination;
use Database\Factories\UserFactory;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $destination= Destination::create([
            'user_id' => '5',
            'dest_owner' => '5',
            'dest_longitude' =>'123.36761830978575',
            'dest_latitude' =>'13.026278035885506',
            'dest_main_picture' => "img/destination_main_pic/100001main.jpg",
            'dest_name' => 'Punta Almara',
            'dest_city' =>'Ligao',
            'dest_address' =>'Sitio Tambac, Maonon, Ligao City',
            'dest_phone' =>'09533067136',
            'dest_email' => 'not specified',
            'dest_date_opened' =>'August 3, 2020',
            'dest_working_hours' =>'Always open',
            'dest_description' => ' In Punta Almara, feel the air and let your spirit soar. This is one of Ligao City\'s well-known beaches. This resort is the greatest location to go if you want to party and want to enjoy the peculiar nightlife of Boracay. You do not have to travel far to join a beach party in the midst of nature. You can get there and listen to the calming sounds of the sea waves for just around an hour\'s journey from Ligao City.',
            'dest_direction' =>'Take Ligao-Pioduran Road',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Php 50 per pax',
            'dest_category' =>'Beach ',
            'dest_fb' =>'https://www.facebook.com/puntaalmara',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'1',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '6',
            'dest_owner' => '6',
            'dest_longitude' =>'123.50719640003031',
            'dest_latitude' =>'13.301103423088552',
            'dest_main_picture' => "img/destination_main_pic/100002main.jpg",
            'dest_name' => 'JMP Adventure Park - Stairways to Haven',
            'dest_city' =>'Polangui',
            'dest_address' =>'Purok 3, Sta. Cruz, Polangui, Albay',
            'dest_phone' =>'09162585415',
            'dest_email' => 'joelpimentel87@gmail.com',
            'dest_date_opened' =>'October 24, 2022',
            'dest_working_hours' =>'Monday-Thursday (6:00 am - 8:00 pm)
Friday-Sunday (6:00 am - 10:00 pm)',
            'dest_description' => ' Experience this newly established ecopark in Polangui, Albay. Admire and capture its beauty together with your loved ones.',
            'dest_direction' =>'15 minutes from Polangui proper:
* From Polangui proper, take the route going to Polangui/Buhi road(Sugcad/Polangui Cemetery/BUPC)
* Go straight all the way to Barangay Cepres(waiting shed)then turn right, once you reach the waiting shed in Sta Cruz, turn right.
* Go straight and you will see the JMP Adventure Park signages.
For commuters ( yellow trike located in front of PMM Upland toda)',
            'dest_fare' =>'250 - 300 pesos',
            'dest_entrance_fee' =>'Daytime - Php 50
Overnight/Camping - Php 150',
            'dest_category' =>'Private Park',
            'dest_fb' =>'https://www.facebook.com/JMPAdventurePark',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '7',
            'dest_owner' => null,
            'dest_longitude' =>'123.30249592842138',
            'dest_latitude' =>'13.036936927771668',
            'dest_main_picture' => "img/destination_main_pic/100003main.jpg",
            'dest_name' => 'Casa Mamita Farm and Beach Resort',
            'dest_city' =>'Oas',
            'dest_address' =>'Badian, Oas, Albay',
            'dest_phone' =>'09171372956',
            'dest_email' => 'not specified',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'Always open',
            'dest_description' => ' Casa Mamita is a 12 hectare farm and beach resort situated in Badian, OAS coastal area, Albay, it is 2-3 hours away from Legazpi City Airport. Access going to the resort is via car or jeepney from Polangui LCC or via bus from Pioduran. If traveling on a private vehicle you can take the Libon-Pantao-Badian route or Pioduran-Badian route. The resort is an hour away from the nearest town and is currently providing fan rooms only. All of our guest houses are single detached with their own beach front, toilet & bath, grilling area and kitchen sink. Amenities are the infinity pool, floating kubo, hilltop view deck and farm.',
            'dest_direction' =>'    Ride a jeepney going to Badian, Oas, Albay in the terminal behind LCC Polangui. Tell the driver/\'konduktor\' to drop you in Casa Mamita Farm and Beach Resort. The last trip of jeepneys to Badian is at 2pm',
            'dest_fare' =>'Php 100/way',
            'dest_entrance_fee' =>'Day Tour - Php 100/pax
Overnight - Php 150/pax',
            'dest_category' =>'Beach',
            'dest_fb' =>'https://web.facebook.com/casamamitafarmandbeachresort',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'1',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '8',
            'dest_owner' => '8',
            'dest_longitude' =>'123.7607996363235',
            'dest_latitude' =>'13.260056689799496',
            'dest_main_picture' => "img/destination_main_pic/100004main.jpg",
            'dest_name' => 'The CUBE House',
            'dest_city' =>'Santo Domingo',
            'dest_address' =>'Purok 4, Brgy Sta.Misericordia, Santo Domingo, Albay',
            'dest_phone' =>'09473259916',
            'dest_email' => 'malizb615@gmail.com',
            'dest_date_opened' =>'November 16, 2021',
            'dest_working_hours' =>'Day tour is from 9 to 5pm
Overnight is from 7pm to 8am',
            'dest_description' => ' The CUBE House is an artistically pleasing lodging that takes advantage of its surroundings. It was constructed alongside a highway and has all the modern conveniences you could desire, yet despite this, it manages to give the impression that you are in the middle of nature since trees and plants have actually been planted all around the facility.',
            'dest_direction' =>'not specified',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'See Amenities to know the Rates',
            'dest_category' =>'Swimming Pool',
            'dest_fb' =>'https://web.facebook.com/TheCUBEHousebyMalizBustamante',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '9',
            'dest_owner' => null,
            'dest_longitude' =>'123.730280889',
            'dest_latitude' =>'13.1569311984',
            'dest_main_picture' => "img/destination_main_pic/100005main.jpg",
            'dest_name' => 'Albay Park and Wildlife',
            'dest_city' =>'Legazpi',
            'dest_address' =>'Bogtong, Legazpi City, Albay',
            'dest_phone' =>'09528242804',
            'dest_email' => 'not specified',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'6:00 am to 8:00 pm',
            'dest_description' => ' Albay Park and Wildlife is a combination of a park and a zoo. With a very affordable entrance fee, visitors can already witness different kinds of animals. They can even enjoy the park\'s amenities and facilities.',
            'dest_direction' =>'    From Manila, one can book a direct flight to Legazpi City. The flight would take an hour, however it can be expensive. For those who wants to save money and a lot of time to spend, they can ride a bus that is travelling towards Legazpi, City. Through this, their approximated travel time is 12 hours.
    As they arrived in Legazpi City, they can ride a jeepney going to Albay Park and Wildlife. Find for Daraga bound jeepney and ask the driver if they will pass to the said park. If they do, tell them to drop you there.',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Adult - Php 50
Child - Php 20',
            'dest_category' =>'Wildlife',
            'dest_fb' =>'https://web.facebook.com/AlbayParkWildlife',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'1',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '10',
            'dest_owner' => null,
            'dest_longitude' =>'123.6712490973966',
            'dest_latitude' =>'13.284602664246865',
            'dest_main_picture' => "img/destination_main_pic/100006main.jpg",
            'dest_name' => 'Mayon Skyline View Deck',
            'dest_city' =>'Tabaco',
            'dest_address' =>'Brgy. Buang, Tabaco City, Albay',
            'dest_phone' =>'not specified',
            'dest_email' => 'not specified',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'Always open',
            'dest_description' => ' Mayon Skyline View Deck, previously Mayon Resthouse, is located halfway up Mayon Volcano. This is one of the most popular tourist destinations in Albay. A must-see location due to the refreshing breeze, stunning scenery, and unforgettable opportunity to go up close to Mayon Volcano, the most flawlessly sculpted volcano in the entire world.',
            'dest_direction' =>'    The skyline has no public transportation. You can travel there by bringing your car or by jeep or van rental. However, if you\'re feeling adventurous, you can climb from the Barangay Buang turnout point.
    There are jeepneys traveling to Ligao City from Tabaco City. You can begin trekking by instructing the vehicle to drop you off at the Mayon entrance in Barangay Buang. Three hours are the estimated duration.',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'No entrance fee',
            'dest_category' =>'Public Park',
            'dest_fb' =>'',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'1',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '11',
            'dest_owner' => '11',
            'dest_longitude' =>'123.71590261443319',
            'dest_latitude' =>'13.128676167983658',
            'dest_main_picture' => "img/destination_main_pic/100007main.jpg",
            'dest_name' => 'Farm Plate',
            'dest_city' =>'Daraga',
            'dest_address' =>'Gabawan, Daraga, Albay',
            'dest_phone' =>'09209235273',
            'dest_email' => 'farmplatenature@gmail.com',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'Monday to Thursday 8am - 9pm
Friday to Sunday 8am - 10pm',
            'dest_description' => ' A relaxed and beautiful farm is located just five and a half kilometers from Legazpi Airport where you can unwind and take in the best of nature. For those who want to quickly escape the bustle of the city or who want to come back in touch with nature, FarmPlate is the ideal option.',
            'dest_direction' =>'    From Caltex, Daraga, you can ride on a tricycle going to Gabawan, Daraga, and tell the driver to get you to FarmPlate.',
            'dest_fare' =>'Caltex Daraga to FarmPlate - Php 25/passenger
FarmPlate to Caltex Daraga - Php 15/passenger',
            'dest_entrance_fee' =>'Php 60 for Kids (below 12 years old)
• Php 85 for Adults',
            'dest_category' =>'Farm',
            'dest_fb' =>'https://web.facebook.com/FarmPlateAlbay',
            'dest_twt' =>'',
            'dest_ig' =>'https://www.instagram.com/farmplatealbay/',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '12',
            'dest_owner' => null,
            'dest_longitude' =>'123.73499504603173',
            'dest_latitude' =>'13.308398919411504',
            'dest_main_picture' => "img/destination_main_pic/100008main.jpeg",
            'dest_name' => 'Busay Falls',
            'dest_city' =>'Malilipot',
            'dest_address' =>'Sta.Teresa Malilipot ,Albay',
            'dest_phone' =>'not specified',
            'dest_email' => 'not specified',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'5:00 am to 5:00 pm',
            'dest_description' => ' Busay Falls is among the natural wonders tucked away in the province of Albay, with its astounding height, crystal-clear water, and distinctive rock formations. Due to its seven-tiered cascade of white foam, it is regarded as one of the highest waterfalls in the nation. Its vital height is thought to be 800 feet from the top. Hundreds of bathers could cool down from the blazing summer heat in the first catch basin that forms below. It can only be accessed by foot route.',
            'dest_direction' =>'    From Tabaco City, ride a jeep going to San Jose, drop off at Sta. Teresa crossing, then ride a pedicab or “padyak” going up the 1st falls.
    From Legazpi City, ride a jeep or filcab express going to Tabaco City, drop off Sta. Teresa intersection, then rides a pedicab or “padyak” going up the 1st falls.',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Php 10',
            'dest_category' =>'Waterfall',
            'dest_fb' =>'',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '13',
            'dest_owner' => null,
            'dest_longitude' =>'123.70174902684298',
            'dest_latitude' =>'13.164512708310914',
            'dest_main_picture' => "img/destination_main_pic/100009main.jpg",
            'dest_name' => 'National Museum Bicol',
            'dest_city' =>'Daraga',
            'dest_address' =>'Busay, Daraga, Albay',
            'dest_phone' =>'09190779850',
            'dest_email' => 'bicol@nationalmuseum.gov.ph',
            'dest_date_opened' =>'October 7, 2022',
            'dest_working_hours' =>'Tuesdays to Sundays, 9am to 4pm',
            'dest_description' => ' Your National Museum in Bicol is a natural history museum furnished with indoor and outdoor exhibitions to enrich your knowledge about Bicol’s natural heritage.
The indoor exhibition includes four (4) permanent galleries with displays of botanical, zoological, and geological specimens that represent Bicol’s unique natural history. It features Bicol’s important geological structures and landforms, rocks, fossils, plants, and animals. The exhibition highlights the volcanoes of Bicol where students and guests can closely study how these mountains of lava were formed.
    On the other hand, the outdoor exhibition includes a garden of volcanic rocks, a butterfly garden, and a nursery of economically important plants in Bicol. A viewing deck is also available to view Mayon, a rare volcanic landform. The visitors will surely deepen their appreciation for nature especially with propagation activities at the butterfly garden. ',
            'dest_direction' =>'not specified',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Free Admission',
            'dest_category' =>'Museum',
            'dest_fb' =>'https://web.facebook.com/nmbicol',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' => '',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '14',
            'dest_owner' => null,
            'dest_longitude' =>'123.60913073911289',
            'dest_latitude' =>'13.300732680379355',
            'dest_main_picture' => "img/destination_main_pic/100010main.jpg",
            'dest_name' => 'The Campsite Mt. Masaraga',
            'dest_city' =>'Ligao',
            'dest_address' =>'Sitio Sabloyon Brgy Amtic, Ligao City, Albay',
            'dest_phone' =>'09175008660',
            'dest_email' => 'thecampsite@gmail.com',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'Always open',
            'dest_description' =>'  An attraction with an aesthetically pleasing overlooking view. A destination where one can enjoy biking, hiking, playing sports, and even camping.',
            'dest_direction' =>'not specified',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Daytime Php 30
Overnight Php 100',
            'dest_category' =>'Mountain',
            'dest_fb' =>'https://web.facebook.com/thecampsite.mt.masaraga',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'1',
            'hidden_gem' =>'0',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        // New Destinations
        $destination= Destination::create([
            'user_id' => '15',
            'dest_owner' => null,
            'dest_longitude' =>'123.52126178969252',
            'dest_latitude' =>'13.195267671157156',
            'dest_main_picture' => "img/destination_main_pic/tigbao.jpg",
            'dest_name' => 'Tigbao Highlands',
            'dest_city' =>'Ligao',
            'dest_address' =>'Tigbao Oma-Oma, Ligao City',
            'dest_phone' =>'Not specified',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>'not specified',
            'dest_working_hours' =>'Always open',
            'dest_description' =>'Think big skies, mind blowing landscape, superb sceneries and hospitable people – and you’ve got Tigbao Highlands. There’s natural playground which begs to be explored.',
            'dest_direction' =>'not specified',
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Not Specified',
            'dest_category' =>'Mountain',
            'dest_fb' =>'https://www.facebook.com/tigbaohighlands/',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '17',
            'dest_owner' => null,
            'dest_longitude' =>'123.43106566374915',
            'dest_latitude' =>'13.083392752403036',
            'dest_main_picture' => "img/destination_main_pic/buhawi.jpg",
            'dest_name' => 'Buhawi Hills Eco-Trek Adventure',
            'dest_city' =>'Pioduran',
            'dest_address' =>'Panganiran, Pioduran',
            'dest_phone' =>' 09558044035',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>"not specified",
            'dest_working_hours' =>'Always open',
            'dest_description' =>"An emerging hiking area for everyone to conquer.
(You can't hike without going to Municipal Tourism & Cultural Affairs Office.)",
            'dest_direction' =>"DARAGA - POLANGUI - LIGAO
- Jeep from Ligao to Caratagan Pioduran (Approximately 1hr 30mins – 2hrs)
- Tricy from Caratagan to La Medalla ( approximately 5-10mins)
- Rent a Habal-habal From La Medalla to Panganiran (30-45mins)
- From La Medalla to Buhawi Hills.( appoximately 1hr 30 mins – 2hrs)",
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Php 200.00/per head environmental fee + entrance fee
Php 500.00 Mountain Guide (Good for 5 pax)
Php 300.00/per head Habal-Habal (Back & Fort)',
            'dest_category' =>'Hills',
            'dest_fb' =>'https://www.facebook.com/pages/Buhawi%20Hills,%20Panganiran%20Pio%20Duran%20Albay/115114796711992',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '18',
            'dest_owner' => null,
            'dest_longitude' =>'123.59230931502758',
            'dest_latitude' =>'13.375384449823049',
            'dest_main_picture' => "img/destination_main_pic/batag.jpg",
            'dest_name' => 'Batag Falls',
            'dest_city' =>'Malinao',
            'dest_address' =>'Sitio Batag Barangay Quinarabasahan, Malinao',
            'dest_phone' =>'Not specified',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>"not specified",
            'dest_working_hours' =>'Always open',
            'dest_description' =>"A fall where you can fall in love with nature and its beauty.",
            'dest_direction' =>"4 km from Barangay Bulang, Malinao. It takes 1 and a half hour of normal walking condition.",
            'dest_fare' =>'not specified',
            'dest_entrance_fee' =>'Varies',
            'dest_category' =>'Falls',
            'dest_fb' =>'https://www.facebook.com/people/Batag-falls-Quinarabasahan-Malinao-Albay/100064113341382/',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '19',
            'dest_owner' => null,
            'dest_longitude' =>'123.62023232736577',
            'dest_latitude' =>'13.408695128649262',
            'dest_main_picture' => "img/destination_main_pic/wildboar.jpg",
            'dest_name' => 'Wild Boar Peak',
            'dest_city' =>'Malinao',
            'dest_address' =>'Barangay Sugcad, Malinao',
            'dest_phone' =>'Not specified',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>"not specified",
            'dest_working_hours' =>'Always open',
            'dest_description' =>"A Mt. Malinao hidden hiking area where everyone can see the glimpse of Albay from above.",
            'dest_direction' =>"Not specified",
            'dest_fare' =>'Not specified',
            'dest_entrance_fee' =>'Not specified',
            'dest_category' =>'Hills',
            'dest_fb' =>'https://www.facebook.com/people/Batag-falls-Quinarabasahan-Malinao-Albay/100064113341382/',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '20',
            'dest_owner' => null,
            'dest_longitude' =>'123.69234039486699',
            'dest_latitude' =>'13.357627584095804',
            'dest_main_picture' => "img/destination_main_pic/hiraya.jpg",
            'dest_name' => 'Hiraya Manawari Nature Park',
            'dest_city' =>'Tabaco',
            'dest_address' =>'San Vicente, Tabaco City',
            'dest_phone' =>'Not specified',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>"not specified",
            'dest_working_hours' =>'7:00AM to 8:30PM',
            'dest_description' =>"Once an empty parcel of land was transformed into a beautiful nature park using upcycled trash.",
            'dest_direction' =>"Not specified",
            'dest_fare' =>'Not specified',
            'dest_entrance_fee' =>'Not specified',
            'dest_category' =>'Park',
            'dest_fb' =>'https://www.facebook.com/hirayamanawaripark/',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '21',
            'dest_owner' => null,
            'dest_longitude' =>'123.61149465847637',
            'dest_latitude' =>'13.05105205891133',
            'dest_main_picture' => "img/destination_main_pic/mayanpayan.jpg",
            'dest_name' => 'Mayanpayan Hills Campsite and Natural Park',
            'dest_city' =>'Jovellar',
            'dest_address' =>'San Roque, Jovellar',
            'dest_phone' =>'Not specified',
            'dest_email' => 'Not specified',
            'dest_date_opened' =>"Not specified",
            'dest_working_hours' =>'Not specified',
            'dest_description' =>"Another natural wonder of nature endowed to the people of municipality of Jovellar. Come and experience the breathtaking view of Jovellar.",
            'dest_direction' =>"No jeep, habal habal (motor) you rent to get here.",
            'dest_fare' =>'Not specified',
            'dest_entrance_fee' =>'Not specified',
            'dest_category' =>'Hills',
            'dest_fb' =>'https://www.facebook.com/mayanpayanhillsJovellarAlbayBicolPh/',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
        $destination= Destination::create([
            'user_id' => '22',
            'dest_owner' => null,
            'dest_longitude' =>'123.6311516688856',
            'dest_latitude' =>'13.032110062727805',
            'dest_main_picture' => "img/destination_main_pic/nabasan.jpg",
            'dest_name' => 'Nabasan Milaos Cave',
            'dest_city' =>'Daraga',
            'dest_address' =>'Nabasan, Daraga',
            'dest_phone' =>'Not specified',
            'dest_email' => 'nabasandaragaalbay@gmail.com',
            'dest_date_opened' =>"Not specified",
            'dest_working_hours' =>'Not specified',
            'dest_description' =>"The newly discovered underground cave. ",
            'dest_direction' =>"No jeep, habal habal (motor) you rent to get here.",
            'dest_fare' =>'Not specified',
            'dest_entrance_fee' =>'Not specified',
            'dest_category' =>'Cave',
            'dest_fb' =>'https://www.facebook.com/nabasanmilaoscave',
            'dest_twt' =>'',
            'dest_ig' =>'',
            'dest_web' =>'',
            'famous' =>'0',
            'hidden_gem' =>'1',
            'dest_approval' =>'Approved',
            'dest_reasons' =>'',
            'dest_rating_average'=> '0'
        ]);
    }
}
